deploy:
  image: node:20-slim
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - mkdir -p ./deploy
    - cp -r ./project/* ./deploy/
    - cp -r ./lib ./deploy/lib
    - grep -rl "'../lib/" ./deploy/ | xargs sed -i "s|'../lib/|'./lib/|g"
    - grep -rl '"../lib/' ./deploy/ | xargs sed -i 's|"../lib/|"./lib/|g'
    - wrangler pages deploy ./deploy --project-name "cgra-t10-g06" --branch "main"